spring:
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password: sa

  h2:
    console:
      enabled: true

  messages:
    basename: i18n/exception
    encoding: UTF-8

jwt :
  token :
    header :
      name : X-AUTH-TOKEN
    creation :
      secretkey : jwtpractice

