spring:
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password: sa

  h2:
    console:
      enabled: true
naver:
  client : 3qhnohQFlOOJ35B5M5Mi
  secret : 9dBljS5fjJ

jwt :
  token :
    header :
      name : X-AUTH-TOKEN
    creation :
      secretkey : jwtpractice

