spring:
# DataSource
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
  h2:
    console:
      enabled: true
# MessageSource
  messages:
    basename: i18n/exception
    encoding: UTF-8
# jwt
jwt :
  token :
    header :
      name : 'X-AUTH-TOKEN'
    creation :
      secretkey : F8EF2B7B714159E608B069CE575B1ED4F2366EFB893856DC9AA2E3BDFE2E6B3B
server:
  port: 8090
